language: python
python:
  - "3.5"

before_install:
  - nvm install 4.6
  - nvm use 4.6

install:
  - pip install -r web/app/requirements.txt
  - cd web
  - npm install

before_script:
  - pip freeze

script:
  - cd app
  - py.test