web:
  restart: always
  build: ./web
  env_file: .env
  environment:
    - OAUTHLIB_INSECURE_TRANSPORT=1 # remove this on production
    - OAUTHLIB_RELAX_TOKEN_SCOPE=1 # remove this on production
  links:
    - postgres:postgres
  volumes:
    - './web/app:/web/app'
    - './web/logs:/web/logs'
  ports:
    - 8000:80
    - 8001:443
  command: python /web/app/main.py # Remove this line to use uwsgi

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
    image: 'postgres:9.4'
    volumes_from:
      - data
    ports:
      - 5432:5432